/**
 * This class is generated by jOOQ
 */
package service.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import service.Keys;
import service.Public;
import service.tables.records.TbExpensesRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbExpenses extends TableImpl<TbExpensesRecord> {

    private static final long serialVersionUID = -2019551049;

    /**
     * The reference instance of <code>public.tb_expenses</code>
     */
    public static final TbExpenses TB_EXPENSES = new TbExpenses();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbExpensesRecord> getRecordType() {
        return TbExpensesRecord.class;
    }

    /**
     * The column <code>public.tb_expenses.id</code>.
     */
    public final TableField<TbExpensesRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('expenses_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tb_expenses.description</code>.
     */
    public final TableField<TbExpensesRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * The column <code>public.tb_expenses.cost</code>.
     */
    public final TableField<TbExpensesRecord, Float> COST = createField("cost", org.jooq.impl.SQLDataType.REAL.nullable(false), this, "");

    /**
     * The column <code>public.tb_expenses.employee_id</code>.
     */
    public final TableField<TbExpensesRecord, Integer> EMPLOYEE_ID = createField("employee_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>public.tb_expenses</code> table reference
     */
    public TbExpenses() {
        this("tb_expenses", null);
    }

    /**
     * Create an aliased <code>public.tb_expenses</code> table reference
     */
    public TbExpenses(String alias) {
        this(alias, TB_EXPENSES);
    }

    private TbExpenses(String alias, Table<TbExpensesRecord> aliased) {
        this(alias, aliased, null);
    }

    private TbExpenses(String alias, Table<TbExpensesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TbExpensesRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TB_EXPENSES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TbExpensesRecord> getPrimaryKey() {
        return Keys.EXPENSES_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TbExpensesRecord>> getKeys() {
        return Arrays.<UniqueKey<TbExpensesRecord>>asList(Keys.EXPENSES_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TbExpensesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TbExpensesRecord, ?>>asList(Keys.TB_EXPENSES__EXPENSES_EMPLOYEE_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbExpenses as(String alias) {
        return new TbExpenses(alias, this);
    }

    /**
     * Rename this table
     */
    public TbExpenses rename(String name) {
        return new TbExpenses(name, null);
    }
}
