/**
 * This class is generated by jOOQ
 */
package dao;


import dao.tables.Category;
import dao.tables.Client;
import dao.tables.Employee;
import dao.tables.Expenses;
import dao.tables.Goods;
import dao.tables.Sale;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -20267597;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.category</code>.
     */
    public final Category CATEGORY = dao.tables.Category.CATEGORY;

    /**
     * The table <code>public.client</code>.
     */
    public final Client CLIENT = dao.tables.Client.CLIENT;

    /**
     * The table <code>public.employee</code>.
     */
    public final Employee EMPLOYEE = dao.tables.Employee.EMPLOYEE;

    /**
     * The table <code>public.expenses</code>.
     */
    public final Expenses EXPENSES = dao.tables.Expenses.EXPENSES;

    /**
     * The table <code>public.goods</code>.
     */
    public final Goods GOODS = dao.tables.Goods.GOODS;

    /**
     * The table <code>public.sale</code>.
     */
    public final Sale SALE = dao.tables.Sale.SALE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.CATEGORY_ID_SEQ,
            Sequences.CLIENT_ID_SEQ,
            Sequences.EMPLOYEE_ID_SEQ,
            Sequences.EXPENSES_ID_SEQ,
            Sequences.PRODUTO_ID_SEQ,
            Sequences.SALE_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Category.CATEGORY,
            Client.CLIENT,
            Employee.EMPLOYEE,
            Expenses.EXPENSES,
            Goods.GOODS,
            Sale.SALE);
    }
}
