/**
 * This class is generated by jOOQ
 */
package dao;


import dao.tables.Category;
import dao.tables.Client;
import dao.tables.Employee;
import dao.tables.Expenses;
import dao.tables.Goods;
import dao.tables.Sale;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.category</code>.
     */
    public static final Category CATEGORY = dao.tables.Category.CATEGORY;

    /**
     * The table <code>public.client</code>.
     */
    public static final Client CLIENT = dao.tables.Client.CLIENT;

    /**
     * The table <code>public.employee</code>.
     */
    public static final Employee EMPLOYEE = dao.tables.Employee.EMPLOYEE;

    /**
     * The table <code>public.expenses</code>.
     */
    public static final Expenses EXPENSES = dao.tables.Expenses.EXPENSES;

    /**
     * The table <code>public.goods</code>.
     */
    public static final Goods GOODS = dao.tables.Goods.GOODS;

    /**
     * The table <code>public.sale</code>.
     */
    public static final Sale SALE = dao.tables.Sale.SALE;
}
