/**
 * This class is generated by jOOQ
 */
package dao.tables;


import dao.Keys;
import dao.Public;
import dao.tables.records.EmployeeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Employee extends TableImpl<EmployeeRecord> {

    private static final long serialVersionUID = 1889720219;

    /**
     * The reference instance of <code>public.employee</code>
     */
    public static final Employee EMPLOYEE = new Employee();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EmployeeRecord> getRecordType() {
        return EmployeeRecord.class;
    }

    /**
     * The column <code>public.employee.id</code>.
     */
    public final TableField<EmployeeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('employee_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.employee.name</code>.
     */
    public final TableField<EmployeeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(70).nullable(false), this, "");

    /**
     * The column <code>public.employee.data_of_birth</code>.
     */
    public final TableField<EmployeeRecord, String> DATA_OF_BIRTH = createField("data_of_birth", org.jooq.impl.SQLDataType.CHAR.length(8).nullable(false), this, "");

    /**
     * The column <code>public.employee.phone</code>.
     */
    public final TableField<EmployeeRecord, String> PHONE = createField("phone", org.jooq.impl.SQLDataType.CHAR.length(11).nullable(false), this, "");

    /**
     * The column <code>public.employee.email</code>.
     */
    public final TableField<EmployeeRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(60), this, "");

    /**
     * The column <code>public.employee.cpf</code>.
     */
    public final TableField<EmployeeRecord, String> CPF = createField("cpf", org.jooq.impl.SQLDataType.CHAR.length(11).nullable(false), this, "");

    /**
     * The column <code>public.employee.username</code>.
     */
    public final TableField<EmployeeRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(15).nullable(false), this, "");

    /**
     * The column <code>public.employee.password</code>.
     */
    public final TableField<EmployeeRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(10).nullable(false), this, "");

    /**
     * The column <code>public.employee.type</code>.
     */
    public final TableField<EmployeeRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * The column <code>public.employee.agency</code>.
     */
    public final TableField<EmployeeRecord, String> AGENCY = createField("agency", org.jooq.impl.SQLDataType.VARCHAR.length(8), this, "");

    /**
     * The column <code>public.employee.count</code>.
     */
    public final TableField<EmployeeRecord, String> COUNT = createField("count", org.jooq.impl.SQLDataType.VARCHAR.length(12), this, "");

    /**
     * The column <code>public.employee.complement</code>.
     */
    public final TableField<EmployeeRecord, String> COMPLEMENT = createField("complement", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "");

    /**
     * The column <code>public.employee.number</code>.
     */
    public final TableField<EmployeeRecord, Integer> NUMBER = createField("number", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.employee.city</code>.
     */
    public final TableField<EmployeeRecord, String> CITY = createField("city", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>public.employee.street</code>.
     */
    public final TableField<EmployeeRecord, String> STREET = createField("street", org.jooq.impl.SQLDataType.VARCHAR.length(60).nullable(false), this, "");

    /**
     * The column <code>public.employee.neighborhood</code>.
     */
    public final TableField<EmployeeRecord, String> NEIGHBORHOOD = createField("neighborhood", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

    /**
     * The column <code>public.employee.fs</code>.
     */
    public final TableField<EmployeeRecord, String> FS = createField("fs", org.jooq.impl.SQLDataType.CHAR.length(2).nullable(false), this, "");

    /**
     * Create a <code>public.employee</code> table reference
     */
    public Employee() {
        this("employee", null);
    }

    /**
     * Create an aliased <code>public.employee</code> table reference
     */
    public Employee(String alias) {
        this(alias, EMPLOYEE);
    }

    private Employee(String alias, Table<EmployeeRecord> aliased) {
        this(alias, aliased, null);
    }

    private Employee(String alias, Table<EmployeeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<EmployeeRecord, Integer> getIdentity() {
        return Keys.IDENTITY_EMPLOYEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EmployeeRecord> getPrimaryKey() {
        return Keys.EMPLOYEE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EmployeeRecord>> getKeys() {
        return Arrays.<UniqueKey<EmployeeRecord>>asList(Keys.EMPLOYEE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Employee as(String alias) {
        return new Employee(alias, this);
    }

    /**
     * Rename this table
     */
    public Employee rename(String name) {
        return new Employee(name, null);
    }
}
