/**
 * This class is generated by jOOQ
 */
package dao.tables;


import dao.Keys;
import dao.Public;
import dao.tables.records.GoodsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Goods extends TableImpl<GoodsRecord> {

    private static final long serialVersionUID = -1455469128;

    /**
     * The reference instance of <code>public.goods</code>
     */
    public static final Goods GOODS = new Goods();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GoodsRecord> getRecordType() {
        return GoodsRecord.class;
    }

    /**
     * The column <code>public.goods.id</code>.
     */
    public final TableField<GoodsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('produto_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.goods.code</code>.
     */
    public final TableField<GoodsRecord, Integer> CODE = createField("code", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.goods.price</code>.
     */
    public final TableField<GoodsRecord, Float> PRICE = createField("price", org.jooq.impl.SQLDataType.REAL.nullable(false), this, "");

    /**
     * The column <code>public.goods.name</code>.
     */
    public final TableField<GoodsRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>public.goods.description</code>.
     */
    public final TableField<GoodsRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * The column <code>public.goods.size</code>.
     */
    public final TableField<GoodsRecord, Integer> SIZE = createField("size", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.goods.category_id</code>.
     */
    public final TableField<GoodsRecord, Integer> CATEGORY_ID = createField("category_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>public.goods</code> table reference
     */
    public Goods() {
        this("goods", null);
    }

    /**
     * Create an aliased <code>public.goods</code> table reference
     */
    public Goods(String alias) {
        this(alias, GOODS);
    }

    private Goods(String alias, Table<GoodsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Goods(String alias, Table<GoodsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<GoodsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_GOODS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GoodsRecord> getPrimaryKey() {
        return Keys.GOODS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GoodsRecord>> getKeys() {
        return Arrays.<UniqueKey<GoodsRecord>>asList(Keys.GOODS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<GoodsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<GoodsRecord, ?>>asList(Keys.GOODS__GOODS_CATEGORY_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Goods as(String alias) {
        return new Goods(alias, this);
    }

    /**
     * Rename this table
     */
    public Goods rename(String name) {
        return new Goods(name, null);
    }
}
