/**
 * This class is generated by jOOQ
 */
package service;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import service.tables.TbCategory;
import service.tables.TbClient;
import service.tables.TbEmployee;
import service.tables.TbExpenses;
import service.tables.TbGoods;
import service.tables.TbSale;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1406782642;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.tb_category</code>.
     */
    public final TbCategory TB_CATEGORY = service.tables.TbCategory.TB_CATEGORY;

    /**
     * The table <code>public.tb_client</code>.
     */
    public final TbClient TB_CLIENT = service.tables.TbClient.TB_CLIENT;

    /**
     * The table <code>public.tb_employee</code>.
     */
    public final TbEmployee TB_EMPLOYEE = service.tables.TbEmployee.TB_EMPLOYEE;

    /**
     * The table <code>public.tb_expenses</code>.
     */
    public final TbExpenses TB_EXPENSES = service.tables.TbExpenses.TB_EXPENSES;

    /**
     * The table <code>public.tb_goods</code>.
     */
    public final TbGoods TB_GOODS = service.tables.TbGoods.TB_GOODS;

    /**
     * The table <code>public.tb_sale</code>.
     */
    public final TbSale TB_SALE = service.tables.TbSale.TB_SALE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.CATEGORY_ID_SEQ,
            Sequences.CLIENT_ID_SEQ,
            Sequences.EMPLOYEE_ID_SEQ,
            Sequences.EXPENSES_ID_SEQ,
            Sequences.PRODUTO_ID_SEQ,
            Sequences.SALE_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TbCategory.TB_CATEGORY,
            TbClient.TB_CLIENT,
            TbEmployee.TB_EMPLOYEE,
            TbExpenses.TB_EXPENSES,
            TbGoods.TB_GOODS,
            TbSale.TB_SALE);
    }
}
