/**
 * This class is generated by jOOQ
 */
package service;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.category_id_seq</code>
     */
    public static final Sequence<Long> CATEGORY_ID_SEQ = new SequenceImpl<Long>("category_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.client_id_seq</code>
     */
    public static final Sequence<Long> CLIENT_ID_SEQ = new SequenceImpl<Long>("client_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.employee_id_seq</code>
     */
    public static final Sequence<Long> EMPLOYEE_ID_SEQ = new SequenceImpl<Long>("employee_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.expenses_id_seq</code>
     */
    public static final Sequence<Long> EXPENSES_ID_SEQ = new SequenceImpl<Long>("expenses_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.produto_id_seq</code>
     */
    public static final Sequence<Long> PRODUTO_ID_SEQ = new SequenceImpl<Long>("produto_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.sale_id_seq</code>
     */
    public static final Sequence<Long> SALE_ID_SEQ = new SequenceImpl<Long>("sale_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
