/**
 * This class is generated by jOOQ
 */
package service;


import javax.annotation.Generated;

import service.tables.TbCategory;
import service.tables.TbClient;
import service.tables.TbEmployee;
import service.tables.TbExpenses;
import service.tables.TbGoods;
import service.tables.TbSale;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.tb_category</code>.
     */
    public static final TbCategory TB_CATEGORY = service.tables.TbCategory.TB_CATEGORY;

    /**
     * The table <code>public.tb_client</code>.
     */
    public static final TbClient TB_CLIENT = service.tables.TbClient.TB_CLIENT;

    /**
     * The table <code>public.tb_employee</code>.
     */
    public static final TbEmployee TB_EMPLOYEE = service.tables.TbEmployee.TB_EMPLOYEE;

    /**
     * The table <code>public.tb_expenses</code>.
     */
    public static final TbExpenses TB_EXPENSES = service.tables.TbExpenses.TB_EXPENSES;

    /**
     * The table <code>public.tb_goods</code>.
     */
    public static final TbGoods TB_GOODS = service.tables.TbGoods.TB_GOODS;

    /**
     * The table <code>public.tb_sale</code>.
     */
    public static final TbSale TB_SALE = service.tables.TbSale.TB_SALE;
}
