/**
 * This class is generated by jOOQ
 */
package dao.tables.records;


import dao.tables.Client;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClientRecord extends UpdatableRecordImpl<ClientRecord> implements Record6<Integer, String, String, String, Float, Float> {

    private static final long serialVersionUID = 1419412294;

    /**
     * Setter for <code>public.client.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.client.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.client.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.client.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.client.date_of_birth</code>.
     */
    public void setDateOfBirth(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.client.date_of_birth</code>.
     */
    public String getDateOfBirth() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.client.phone</code>.
     */
    public void setPhone(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.client.phone</code>.
     */
    public String getPhone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.client.amount_spent</code>.
     */
    public void setAmountSpent(Float value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.client.amount_spent</code>.
     */
    public Float getAmountSpent() {
        return (Float) get(4);
    }

    /**
     * Setter for <code>public.client.balance</code>.
     */
    public void setBalance(Float value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.client.balance</code>.
     */
    public Float getBalance() {
        return (Float) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, Float, Float> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, Float, Float> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Client.CLIENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Client.CLIENT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Client.CLIENT.DATE_OF_BIRTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Client.CLIENT.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field5() {
        return Client.CLIENT.AMOUNT_SPENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field6() {
        return Client.CLIENT.BALANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDateOfBirth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value5() {
        return getAmountSpent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value6() {
        return getBalance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClientRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClientRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClientRecord value3(String value) {
        setDateOfBirth(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClientRecord value4(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClientRecord value5(Float value) {
        setAmountSpent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClientRecord value6(Float value) {
        setBalance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClientRecord values(Integer value1, String value2, String value3, String value4, Float value5, Float value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClientRecord
     */
    public ClientRecord() {
        super(Client.CLIENT);
    }

    /**
     * Create a detached, initialised ClientRecord
     */
    public ClientRecord(Integer id, String name, String dateOfBirth, String phone, Float amountSpent, Float balance) {
        super(Client.CLIENT);

        set(0, id);
        set(1, name);
        set(2, dateOfBirth);
        set(3, phone);
        set(4, amountSpent);
        set(5, balance);
    }
}
