/**
 * This class is generated by jOOQ
 */
package service.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import service.tables.TbClient;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbClientRecord extends UpdatableRecordImpl<TbClientRecord> implements Record7<Integer, String, String, String, Double, Double, String> {

    private static final long serialVersionUID = 99396043;

    /**
     * Setter for <code>public.tb_client.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tb_client.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.tb_client.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tb_client.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tb_client.date_of_birth</code>.
     */
    public void setDateOfBirth(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tb_client.date_of_birth</code>.
     */
    public String getDateOfBirth() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tb_client.phone</code>.
     */
    public void setPhone(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tb_client.phone</code>.
     */
    public String getPhone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tb_client.amount_spent</code>.
     */
    public void setAmountSpent(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tb_client.amount_spent</code>.
     */
    public Double getAmountSpent() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>public.tb_client.balance</code>.
     */
    public void setBalance(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tb_client.balance</code>.
     */
    public Double getBalance() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>public.tb_client.email</code>.
     */
    public void setEmail(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.tb_client.email</code>.
     */
    public String getEmail() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, Double, Double, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, Double, Double, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TbClient.TB_CLIENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TbClient.TB_CLIENT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TbClient.TB_CLIENT.DATE_OF_BIRTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TbClient.TB_CLIENT.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return TbClient.TB_CLIENT.AMOUNT_SPENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return TbClient.TB_CLIENT.BALANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TbClient.TB_CLIENT.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDateOfBirth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getAmountSpent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getBalance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbClientRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbClientRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbClientRecord value3(String value) {
        setDateOfBirth(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbClientRecord value4(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbClientRecord value5(Double value) {
        setAmountSpent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbClientRecord value6(Double value) {
        setBalance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbClientRecord value7(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbClientRecord values(Integer value1, String value2, String value3, String value4, Double value5, Double value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbClientRecord
     */
    public TbClientRecord() {
        super(TbClient.TB_CLIENT);
    }

    /**
     * Create a detached, initialised TbClientRecord
     */
    public TbClientRecord(Integer id, String name, String dateOfBirth, String phone, Double amountSpent, Double balance, String email) {
        super(TbClient.TB_CLIENT);

        set(0, id);
        set(1, name);
        set(2, dateOfBirth);
        set(3, phone);
        set(4, amountSpent);
        set(5, balance);
        set(6, email);
    }
}
