/**
 * This class is generated by jOOQ
 */
package service.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;

import service.tables.TbEmployee;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbEmployeeRecord extends UpdatableRecordImpl<TbEmployeeRecord> implements Record17<Integer, String, String, String, String, String, String, String, String, String, String, String, Integer, String, String, String, String> {

    private static final long serialVersionUID = 1559939402;

    /**
     * Setter for <code>public.tb_employee.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tb_employee.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.tb_employee.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tb_employee.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tb_employee.data_of_birth</code>.
     */
    public void setDataOfBirth(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tb_employee.data_of_birth</code>.
     */
    public String getDataOfBirth() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tb_employee.phone</code>.
     */
    public void setPhone(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tb_employee.phone</code>.
     */
    public String getPhone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tb_employee.email</code>.
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tb_employee.email</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.tb_employee.cpf</code>.
     */
    public void setCpf(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tb_employee.cpf</code>.
     */
    public String getCpf() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.tb_employee.username</code>.
     */
    public void setUsername(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.tb_employee.username</code>.
     */
    public String getUsername() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.tb_employee.password</code>.
     */
    public void setPassword(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.tb_employee.password</code>.
     */
    public String getPassword() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.tb_employee.type</code>.
     */
    public void setType(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.tb_employee.type</code>.
     */
    public String getType() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.tb_employee.agency</code>.
     */
    public void setAgency(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.tb_employee.agency</code>.
     */
    public String getAgency() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.tb_employee.count</code>.
     */
    public void setCount(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.tb_employee.count</code>.
     */
    public String getCount() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.tb_employee.complement</code>.
     */
    public void setComplement(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.tb_employee.complement</code>.
     */
    public String getComplement() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.tb_employee.number</code>.
     */
    public void setNumber(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.tb_employee.number</code>.
     */
    public Integer getNumber() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>public.tb_employee.city</code>.
     */
    public void setCity(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.tb_employee.city</code>.
     */
    public String getCity() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.tb_employee.street</code>.
     */
    public void setStreet(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.tb_employee.street</code>.
     */
    public String getStreet() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.tb_employee.district</code>.
     */
    public void setDistrict(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.tb_employee.district</code>.
     */
    public String getDistrict() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.tb_employee.state</code>.
     */
    public void setState(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.tb_employee.state</code>.
     */
    public String getState() {
        return (String) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Integer, String, String, String, String, String, String, String, String, String, String, String, Integer, String, String, String, String> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Integer, String, String, String, String, String, String, String, String, String, String, String, Integer, String, String, String, String> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TbEmployee.TB_EMPLOYEE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TbEmployee.TB_EMPLOYEE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TbEmployee.TB_EMPLOYEE.DATA_OF_BIRTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TbEmployee.TB_EMPLOYEE.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TbEmployee.TB_EMPLOYEE.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TbEmployee.TB_EMPLOYEE.CPF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TbEmployee.TB_EMPLOYEE.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TbEmployee.TB_EMPLOYEE.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TbEmployee.TB_EMPLOYEE.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return TbEmployee.TB_EMPLOYEE.AGENCY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return TbEmployee.TB_EMPLOYEE.COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return TbEmployee.TB_EMPLOYEE.COMPLEMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return TbEmployee.TB_EMPLOYEE.NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return TbEmployee.TB_EMPLOYEE.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return TbEmployee.TB_EMPLOYEE.STREET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return TbEmployee.TB_EMPLOYEE.DISTRICT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return TbEmployee.TB_EMPLOYEE.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDataOfBirth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCpf();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getAgency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getComplement();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getStreet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getDistrict();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbEmployeeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbEmployeeRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbEmployeeRecord value3(String value) {
        setDataOfBirth(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbEmployeeRecord value4(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbEmployeeRecord value5(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbEmployeeRecord value6(String value) {
        setCpf(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbEmployeeRecord value7(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbEmployeeRecord value8(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbEmployeeRecord value9(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbEmployeeRecord value10(String value) {
        setAgency(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbEmployeeRecord value11(String value) {
        setCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbEmployeeRecord value12(String value) {
        setComplement(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbEmployeeRecord value13(Integer value) {
        setNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbEmployeeRecord value14(String value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbEmployeeRecord value15(String value) {
        setStreet(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbEmployeeRecord value16(String value) {
        setDistrict(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbEmployeeRecord value17(String value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbEmployeeRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, Integer value13, String value14, String value15, String value16, String value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbEmployeeRecord
     */
    public TbEmployeeRecord() {
        super(TbEmployee.TB_EMPLOYEE);
    }

    /**
     * Create a detached, initialised TbEmployeeRecord
     */
    public TbEmployeeRecord(Integer id, String name, String dataOfBirth, String phone, String email, String cpf, String username, String password, String type, String agency, String count, String complement, Integer number, String city, String street, String district, String state) {
        super(TbEmployee.TB_EMPLOYEE);

        set(0, id);
        set(1, name);
        set(2, dataOfBirth);
        set(3, phone);
        set(4, email);
        set(5, cpf);
        set(6, username);
        set(7, password);
        set(8, type);
        set(9, agency);
        set(10, count);
        set(11, complement);
        set(12, number);
        set(13, city);
        set(14, street);
        set(15, district);
        set(16, state);
    }
}
