/**
 * This class is generated by jOOQ
 */
package service.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import service.tables.TbExpenses;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbExpensesRecord extends UpdatableRecordImpl<TbExpensesRecord> implements Record4<Integer, String, Double, Integer> {

    private static final long serialVersionUID = -38540379;

    /**
     * Setter for <code>public.tb_expenses.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tb_expenses.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.tb_expenses.description</code>.
     */
    public void setDescription(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tb_expenses.description</code>.
     */
    public String getDescription() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tb_expenses.cost</code>.
     */
    public void setCost(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tb_expenses.cost</code>.
     */
    public Double getCost() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>public.tb_expenses.employee_id</code>.
     */
    public void setEmployeeId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tb_expenses.employee_id</code>.
     */
    public Integer getEmployeeId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Double, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Double, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TbExpenses.TB_EXPENSES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TbExpenses.TB_EXPENSES.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return TbExpenses.TB_EXPENSES.COST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TbExpenses.TB_EXPENSES.EMPLOYEE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getCost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getEmployeeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbExpensesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbExpensesRecord value2(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbExpensesRecord value3(Double value) {
        setCost(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbExpensesRecord value4(Integer value) {
        setEmployeeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbExpensesRecord values(Integer value1, String value2, Double value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbExpensesRecord
     */
    public TbExpensesRecord() {
        super(TbExpenses.TB_EXPENSES);
    }

    /**
     * Create a detached, initialised TbExpensesRecord
     */
    public TbExpensesRecord(Integer id, String description, Double cost, Integer employeeId) {
        super(TbExpenses.TB_EXPENSES);

        set(0, id);
        set(1, description);
        set(2, cost);
        set(3, employeeId);
    }
}
